config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  resources :lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]

  def index
    @lists = List.all
  end

  def show; end

  def new
    @list = List.new
  end

  def edit; end

  def create
    @list = List.new(list_params)

    if @list.save
      turbo_stream
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @list.update(list_params)
      turbo_stream
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    turbo_stream
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar has-shadow is-primary is-spaced" role="navigation" aria-label="main navigation">
    <div class="container">
      <div class="navbar-brand is-flex is-flex-direction-column">
        <%= link_to root_path, class: 'navbar-item py-1' do %>
          <h1 class="title">Four Lists</h1>
        <% end %>

        <small class="navbar-item has-text-black py-0">
          Crie, Configure e compartilhe suas listas.
        </small>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FourLists</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/header'  %>
    
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: [list]) do |f| %>
  <%= f.text_field :name, 
    placeholder: 'Name', 
    autofocus: true
  %>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/lists/_list.html.erb
<%= turbo_frame_tag dom_id(list) do %>
  <li>
    <div>
      <span><%= list.name %></span>
    </div>

    <div>
      <span><%= link_to 'Acessar', list, data: { turbo_frame: :_top } %></span>
    </div>
  </li>
<% end %>

app/views/lists/create.turbo_stream.erb
<%= turbo_stream.append :lists, @list %>
<%= turbo_stream.update dom_id(List.new), "" %>

app/views/lists/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@list) %>

app/views/lists/edit.html.erb
<%= turbo_frame_tag dom_id(@list) do %>
  <%= render 'form', list: @list %>
<% end %>

app/views/lists/index.html.erb
<section>
  <div>
    <h2>Minhas Listas</h2>
  </div>

  <div>
    <%= link_to 'Nova Lista', 
      new_list_path, 
      data: { turbo_frame: dom_id(List.new) }
    %>
  </div>
</section>

<section>
  <%= turbo_frame_tag dom_id(List.new) %>

  <ul> 
    <%= turbo_frame_tag :lists do %>
      <% @lists.each do |list| %>
        <%= render 'list', list: list %>
      <% end %>
    <% end %>
  </ul>
</section>

app/views/lists/new.html.erb
<%= turbo_frame_tag dom_id(List.new) do %>
  <section>
    <%= render 'form', list: @list %>
  </section>
<% end %>

app/views/lists/show.html.erb
<div>
  <div>
    <h2><%= @list.name %>
  </div>

  <div>
    <%= link_to 'Configurações', edit_list_path(@list) %>
  </div>
</div>

app/views/lists/update.turbo_stream.erb
<%= turbo_stream.update dom_id(@list) do %>
  <%= render @list %>
<% end %>